[package]
name = "atcoder_rust"
version = "0.1.0"
authors = ["kanno <kanno@kiseki.systems>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
